---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pods.model-validation.rhtas.redhat.com
  namespace: model-validation-controller
  annotations:
    # OpenShift annotation to request certificate provisioning for the webhook
    admission.k8s.io/webhook-cert-provisioner: "true"
webhooks:
- admissionReviewVersions:
    - v1
  name: "pods.model-validation.rhtas.redhat.com"
  clientConfig:
    service:
      name: model-validation-controller
      namespace: model-validation-controller
      path: /webhook
      port: 443
    caBundle: "${CA_PEM_B64}"
  failurePolicy: Fail
  matchPolicy: Equivalent
  timeoutSeconds: 10
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
  sideEffects: None
  # objectSelector:
  #   matchExpressions:
  #     - key: "validation.rhtas.redhat.com/ml"
  #       operator: Exists
