apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

# No webhook for development - just the basic operator
namespace: model-validation-operator-dev

images:
- name: controller
  newName: controller
  newTag: latest

patches:
- path: development-config.yaml
  target:
    kind: Deployment
    name: controller-manager
- patch: |-
    - op: add
      path: /metadata/labels/validation.ml.sigstore.dev~1ignore
      value: "true"
  target:
    kind: Namespace
