apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: model-validation-operator
    app.kubernetes.io/managed-by: kustomize
  name: model-validation-webhook
  namespace: system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager