---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: model-validation-controller-binding
subjects:
- kind: ServiceAccount
  name: model-validation-controller-sa
  namespace: model-validation-controller
roleRef:
  kind: ClusterRole
  name: modelvalidation-viewer-role
  apiGroup: rbac.authorization.k8s.io
