---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - crd.yaml
 - clusterrole.yaml
 - service_account.yaml
 - clusterrole_binding.yaml
 - example-webhook-tls.yaml
 - deployment.yaml
 - mutation_webhook.yaml
 - service.yaml
