---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pods.model-validation.rhtas.redhat.com
  annotations:
    # OpenShift annotation to request certificate provisioning for the webhook
    admission.k8s.io/webhook-cert-provisioner: "true"
webhooks:
- admissionReviewVersions:
    - v1
  name: "pods.model-validation.rhtas.redhat.com"
  clientConfig:
    service:
      name: model-validation-controller
      namespace: model-validation-controller
      path: /webhook
      port: 443
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVQ0tGV09KOTJjRjlOVzhJWWxtUktKRWJDRnpNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qVXdNVEU0Ck1qQXhOekF3V2hjTk16QXdNVEUzTWpBeE56QXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNTFpKUFQvCk1GODB0WUdVeE9NS0R5RWxKVTVIMGZrazFJVnZtTnRoNlVtRlpOdG8xa1g5ZTBnNmJjUXV3QXpMQUhNUUlKbCsKWHNBWnRtQlJUMEJMcnJHQ3JhVXpZMlkxQjF4YnIrbmF4WlBIN0prKzhqdEtSSUlNMkh0YnA1c0k2OWlUckZrSgpKOG03Z0wwNU9tTGhabUZrbW11NjBtL2dkMWVFQWN5MHVWZEhGTmU2NlgwemM2QVp2ZUdsWEd4WXdsYlZPSy9qClJyUnI0bmFtVmlSMVhMckpxVzlkK29hT0NzdUxQcTh5aDdGbXZHUG1mWUVjL0pDYXpJN1hqTW1jZzViaVJmM3gKL2lLTlJVcU91MkRBUDUzWDZtUFEzV2tDZHBFMlRiTjhpZWlLSjZ5Y1VXM3MxQXJvenRPS2U3SHdSdUNvWFhtVgpkU2xqcGxlUENNdDJSWlVDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkVxalVPY3lxTGQrcmM2UjVNNG13Q0ZBSEtBVU1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUNxN1FnQWZldzg4V1pWMm45YURIRFZqb0VtbU9vTXZjdzRXNUhGZUV2YzlHYXpzSUczQUU0awpzaXlaRDZpYzRNcGdiTm0wVlZVWkhaaGVuRWtvbkFGcjhaZjh4SzJrcXZqRmRmL1lYd09IdmtaSTU5RUJRV1F3ClFIZnhBN2NRQm9OZnhBbVhwRmRlZ0ZHR3oyQkZOblhDd3hiQ2FxKzcrcm1DNnVSTnkvc2UyallqMVl5Z3k4MloKbTliQ1h2QnN4aUphSVJydFo1TVl5OTRlQ1N6NFhtT0xhcEpFcEU3bVU3MWlVUjAvbEtramxqVEdvY3pvQVA4ZAplYTNVUzAvLzBkbkhldGMwQ3R2TTNoZTZtKzdxSDRudlhGOCthNDZwekV5ZHBWemFnTkkxa2VwY3pTQnJ3aWNRClVZSkVyZjdYN3BwbXBkY3gxZTJXVUdib0VjbFk4eXNNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  failurePolicy: Fail
  matchPolicy: Equivalent
  timeoutSeconds: 10
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
  sideEffects: None
  # objectSelector:
  #   matchExpressions:
  #     - key: "validation.rhtas.redhat.com/ml"
  #       operator: Exists
