apiVersion: v1
kind: Service
metadata:
  name: model-validation-webhook
  namespace: system
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: model-validation-operator